DROP TABLE DB1.TABLE1;

CREATE TABLE DB1.CUSTOMER(
C_ID VARCHAR(20) NOT null PRIMARY KEY,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
DOB int,
ADDRESS VARCHAR(100)
);

INSERT INTO DB1.CUSTOMER
VALUES('C001','JIA JIUN', 'NG', 111192, '188, Lonsdale Street Melbourne Victoria 3000');

SELECT * FROM DB1.CUSTOMER;

SELECT FIRST_NAME, LAST_NAME FROM DB1.CUSTOMER
WHERE C_ID = 'C001';

INSERT INTO DB1.CUSTOMER
VALUES('C002', 'JIUN JIA', 'TAN', 121293, '88, Bourke Street Melbourne Victoria 3000');

UPDATE DB1.CUSTOMER
SET LAST_NAME = 'GOH'
WHERE C_ID = 'C001' AND FIRST_NAME = 'JIUN JIA';

UPDATE DB1.CUSTOMER
SET LAST_NAME = 'GOH'
WHERE C_ID = 'C001' AND FIRST_NAME = 'JIA JIUN'; 

SELECT * FROM DB1.CUSTOMER;

DELETE FROM DB1.CUSTOMER
WHERE C_ID = 'C002'; 

SELECT * FROM DB1.CUSTOMER;

SELECT FIRST_NAME FROM DB1.CUSTOMER
GROUP BY FIRST_NAME;

INSERT INTO DB1.CUSTOMER
VALUES('C003', 'NO NO', 'DAVID', 301290, '11, Little Bourke Street Melbourne Victoria 3000');